library kotlin.primitive;

typedef Any = Object?;
typedef Nothing = Never;
typedef Int = int;
typedef Byte = int;
typedef Short = int;
typedef Long = int;
typedef Float = double;
typedef Double = double;
typedef Char = String;
typedef Boolean = bool;
typedef Array<T> = List<T>;
typedef ArrayList<T> = Array<T>;
typedef BooleanArray<T> = Array<Boolean>;
typedef ByteArray<T> = Array<Byte>;
typedef CharArray<T> = Array<Char>;
typedef DoubleArray<T> = Array<Double>;
typedef IntArray<T> = Array<Int>;
typedef FloatArray<T> = Array<Float>;
typedef LongArray<T> = Array<Long>;
typedef ShortArray<T> = Array<Short>;
typedef Unit = void;
